{
  "metadata": {
    "name": "Screensaver",
    "version": "0.0.1",
    "author": "Nik Nikovsky",
    "icon": "@local:icon.png"
  },
  "position": {
    "centered": true,
    "x": 0,
    "y": 0
  },
  "size": {
    "w": 300,
    "h": 300
  },
  "minSize": {
    "w": 300,
    "h": 300
  },
  "maxSize": {
    "w": 1920,
    "h": 1080
  },
  "state": {
    "minimized": false,
    "maximized": true,
    "headless": true,
    "resizable": false,
    "fullscreen": false
  },
  "controls": {
    "minimize": true,
    "maximize": false,
    "close": true
  },
  "glass": true,
  "hidden": false,
  "core": false,
  "entrypoint": "main.js",
  "id": "NikN_Screensaver"
}